### ISSUE TITLE
Files with filenames starting with a dot is not deployed

### ISSUE THREAD

**Issue by egs33** [google-github-actions/deploy-cloud-functions#102]
### TL;DR
Files with filenames starting with a dot (e.g. `.npmrc`) is not deployed.

**Expected behavior**
Deployed like any other file.

`.npmrc` is required to install private node modules.
https://cloud.google.com/functions/docs/writing/specifying-dependencies-nodejs#using_private_modules

**Observed behavior**
The deply action succeeds, but fails to build functions because the file is not uploaded.

### Reproduction

**Action YAML**

```yaml

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add npm credential
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN }}" >> .npmrc

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: *********************
          runtime: nodejs14
          region: asia-northeast1
          credentials: ${{ secrets.CREDENTIALS }}
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: ************************

```
