### ISSUE TITLE
Reuse a zip to deploy all functions

### ISSUE THREAD

**Issue by EvertonTomalok** [google-github-actions/deploy-cloud-functions#116]
### TL;DR

Nowadays, it's necessary to create an action for each function deployment.

It'll be good to have a way to reuse a created zip to deploy other functions inside the same cicle.

### Design

**Action YAML**

A way to pass all functions to be deployed could be very useful

Like:

```
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: deploy-reusing-zip
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: do_another_stuff,another_function,third_function
        runtime: python38
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        region: us-east1
```

**Comment by bharathkkb** [comment]
Hi @EvertonTomalok

Would something like matrix build solve your use-case. We have also improved the zip performance in #101.
```
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
            source_dir: ["another_function","third_function"]

    steps:
    - uses: actions/checkout@v2
    - id: deploy-reusing-zip
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: ${{ matrix.source_dir }}
        source_dir: ${{ matrix.source_dir }}
        runtime: python38
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        region: us-east1
```
