### ISSUE TITLE
No care about memory_mb input

### ISSUE THREAD

**Issue by ygueguin** [google-github-actions/deploy-cloud-functions#154]
### TL;DR

memory_mb input is not apply

**Expected behavior**

memory_mb input is apply 

**Observed behavior**

default value is apply 

### Reproduction

**Action YAML**

```yaml
# Paste your complete GitHub Actions YAML here, removing
# any sensitive values.
- name: Set up Cloud SDK
  uses: google-github-actions/setup-gcloud@master
  with:
    project_id: ${{ steps.secrets.outputs.GCP_LZ_UAT }}
    service_account_key: ${{ steps.secrets.outputs.GCP_SA_KEY }}
    export_default_credentials: true
- id: deploy
  uses: google-github-actions/deploy-cloud-functions@main
  with:
    project_id: ${{ steps.secrets.outputs.GCP_LZ_UAT }}
    name: ${{ steps.secrets.outputs.FUNCTION_NAME }}
    runtime: ${{ steps.secrets.outputs.RUNTIME }}
    entry_point: ${{ steps.secrets.outputs.ENTRY_POINT }}
    memory_mb: 4096MB
    region: ${{ steps.secrets.outputs.REGION }}
    vpc_connector: ${{ steps.secrets.outputs.VPC_CONNECTOR }}
    vpc_connector_egress_settings: ${{ steps.secrets.outputs.VPC_CONNECTOR_EGRESS_SETTINGS }}
    ingress_settings: ${{ steps.secrets.outputs.INGRESS_SETTINGS }}
    event_trigger_type: ${{ steps.secrets.outputs.EVENT_TRIGGER_TYPE }}
    event_trigger_resource: ${{ steps.secrets.outputs.EVENT_TRIGGER_RESOURCE }}
    event_trigger_service: ${{ steps.secrets.outputs.EVENT_TRIGGER_SERVICE }}
    labels: ${{ steps.secrets.outputs.LABELS }}
    service_account_email: ${{ steps.secrets.outputs.SA_MAIL }}
```
