### ISSUE TITLE
Support using secrets

### ISSUE THREAD

**Issue by toga4** [google-github-actions/deploy-cloud-functions#187]
### TL;DR

It would be great if this action supports passing the secret as an environment variable or mounting the secret as a volume.

### Design

**Action YAML**

```yaml
steps:
- uses: actions/checkout@v2
- id: deploy
  uses: google-github-actions/deploy-cloud-functions@main
  with:
    name: my-function
    runtime: nodejs10
    credentials: ${{ secrets.gcp_credentials }}
    secrets: |
      ENV_VAR=SECRET:VERSION
      ENV_VAR=projects/PROJECT_ID/secrets/SECRET:VERSION
      ENV_VAR=projects/PROJECT_ID/secrets/SECRET/versions/VERSION
      /SECRET_PATH=SECRET:VERSION
      /MOUNT_PATH:/SECRET_PATH=SECRET:VERSION

```

**Resources**

- [Using secrets &nbsp;|&nbsp; Cloud Functions Documentation &nbsp;|&nbsp; Google Cloud](https://cloud.google.com/functions/docs/configuring/secrets)
- [gcloud beta functions deploy &nbsp;|&nbsp; Cloud SDK Documentation &nbsp;|&nbsp; Google Cloud](https://cloud.google.com/sdk/gcloud/reference/beta/functions/deploy#--set-secrets)
