### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by TheForgotten69** [google-github-actions/deploy-cloud-functions#21]
### TL;DR

Add the possibility to declare the memory allocated to said function like in CLI.

### Design

**Action YAML**

```yaml
 with:
    name: my-function
    runtime: nodejs10
    credentials: ${{ secrets.gcp_credentials }}
    memory: 128MB
```

**Resources**

- [SDK Gcloud Deploy - Memory](https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--memory)

**Additional information**
