### ISSUE TITLE
Semantics of action changed

### ISSUE THREAD

**Issue by cjanietz** [google-github-actions/deploy-cloud-functions#214]
### TL;DR

With the latest changes, certain settings are now handled differently, which is a breaking change.
For example it seems timeout can no longer be provided as pure number.
The error is:
```
"message": "Invalid value at 'function.timeout' (type.googleapis.com/google.protobuf.Duration), Field 'timeout', Illegal duration format; duration must end with 's'",
```

### Action YAML

```yaml
-   id: Deploy
                uses: google-github-actions/deploy-cloud-functions@main
                with:
                    timeout: 540
```
