### ISSUE TITLE
Environment variable values containing a "=" are cut off

### ISSUE THREAD

**Issue by coolstuff-mikael** [google-github-actions/deploy-cloud-functions#229]
### TL;DR

Using the `env_vars` input parameter, environment variable values that contain equals signs are cut off. This started to happen last week when the parsing method changed from `indexOf` to `split`.

### Expected behavior

Given the input `FOO=bar=baz`. the value of FOO should be `bar=baz`.

### Observed behavior

The value is `bar`.

### Action YAML

```yaml
- name: Deploy
  uses: google-github-actions/deploy-cloud-functions@v0.7.0
  with:
    env_vars: CONN=DefaultEndpointsProtocol=https;AccountName=foo;AccountKey=bar
```

### Additional information

If `split` is preferred over `indexOf`, the following code should have the desired effect:
```
let [k, v] = pair.split((/=(.*)/), 2);
```
