### ISSUE TITLE
Avoiding manual secret variable reset upon deployment

### ISSUE THREAD

**Issue by Resousse** [google-github-actions/deploy-cloud-functions#244]
### TL;DR

For a specific reason, I need to set a secret env variable on a cloud function, manually. But when I deploy the new code of the function via a github action, my manually set env variables are removed.
How to ignore those variable to let them as is?

### Expected behavior

Manually set env variable to be preserved even after an automated deployment

### Observed behavior

Manually set secret env variable are removed after the run of the github actions

### Action YAML

```yaml
- name: Deploy sendEmail
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: sendEmailNotification
        runtime: python39
        entry_point: sendEmailNotification
        region: europe-west1
```

### Additional information

I didn't find any info in the doc about this behavior, it's specified for env variable but not secret variables
