### ISSUE TITLE
Passing the field: `min_instances` does not get applied to the cloud function

### ISSUE THREAD

**Issue by jlazar** [google-github-actions/deploy-cloud-functions#259]
### TL;DR

Passing a `min_instances` of 1 does not modify the actual min instances of the cloud function. 

Below step will not work:
```
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'my-function'
        runtime: 'nodejs12'
        min_instances: 1
```
It seems the root of this issue is that the Cloud Functions API does not have a minInstances defined in its spec: https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#CloudFunction

### Expected behavior

Correctly set the min_instances of the cloud function

### Observed behavior

min_instances for the cloud function was set to 0

### Action YAML

```yaml
name: "Cloud Functions Deploy"

on:
  push:
    branches: [develop]
    paths:
      - functions/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - test1

        include:
          - function: test1
            name: test1
            entry_point: test1
            min_instances: 1

    steps:
      - uses: actions/checkout@v2

      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: yarn install
        run: yarn install

      - name: Typescript compiler
        run: yarn functions build

      - name: Setup GCP Service Account
        uses: google-github-actions/auth@v0.4.1
        with:
          credentials_json: ${{secrets.GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT}}

      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{matrix.name}}
          event_trigger_type: ${{matrix.event_trigger_type}}
          event_trigger_resource: ${{matrix.event_trigger_resource}}
          entry_point: ${{matrix.entry_point}}
          runtime: nodejs14
          region: us-east4
          min_instances: ${{matrix.min_instances}}
```
