### ISSUE TITLE
deploy-cloud-functions reports error when deploying function with Pub/Sub event trigger

### ISSUE THREAD

**Issue by FongMunHong** [google-github-actions/deploy-cloud-functions#278]
### TL;DR

When using deploy-cloud-functions to deploy a function with a Pub/Sub event trigger the github action fails with Error: Cannot read property 'url' of undefined. Although an error is shown the function deploys correctly.

### Expected behavior

The action should report a success.

### Observed behavior

```
Run google-github-actions/deploy-cloud-functions@v0.1.0
Creating a function revision
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Updating function deployment
Function deployment updated
**Error: Cannot read property 'url' of undefined**
```

### Action YAML

```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    
env:
  PROJECT: ${{ secrets.PROJECT_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: deploy cloud function
        id: deploy-background-function
        uses: google-github-actions/deploy-cloud-functions@v0.1.0
        with:
          name: helloWorld
          runtime: python38
          project_id: ${{ env.PROJECT }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          entry_point: helloWorld
          source_dir: src
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/${{ secrets.topic_ID }}
```
