### ISSUE TITLE
Ability to create 2nd Gen functions

### ISSUE THREAD

**Issue by vishnumenon** [google-github-actions/deploy-cloud-functions#304]
### TL;DR

I'd love to take advantage of the new 2nd Gen cloud functions, and it'd be great to deploy them with github actions. Ideally, I'd like to specify the generation of the cloud function as an input in the yaml. Is there currently any way to deploy a 2nd Gen cloud function with a github action, using this repo or another one? 

### Detailed design

```markdown
Something like `gen: 2` as an input option would be perfect
```

**Comment by jwilksy** [comment]
@bharathkkb Is there an update on when this Action will support the ability to set it to deploy using Gen2?

**Comment by sethvargo** [comment]
Hi @jwilksy 

Cloud Functions are still in Preview (https://cloud.google.com/functions/docs/2nd-gen/overview).

**Comment by DeryabinSergey** [comment]
Has someone information about release date 2ng generation?

**Comment by seanemmer** [comment]
This is now in GA - [https://cloud.google.com/blog/products/serverless/cloud-functions-2nd-generation-now-generally-available](https://cloud.google.com/blog/products/serverless/cloud-functions-2nd-generation-now-generally-available)

**Comment by igor-imaginemage** [comment]
I created [this PR](https://github.com/google-github-actions/deploy-cloud-functions/pull/357) to see if we can have this available through this action. I'm available to contribute to this. Please let me know what else is necessary here.

**Comment by ryanwoconnor** [comment]
This feature would be tremendously helpful. Any ETA on this support?

**Comment by akshayshippy** [comment]
+1 would be super helpful to have this as part of the existing github action

**Comment by mymyparty** [comment]
Right now i see errors related to Functions gen 2 like: cannot create a function <name> because it already exists in gen 2

**Comment by sethvargo** [comment]
We do not currently support Cloud Functions gen2. If you need support for gen2, you can use the `setup-gcloud` action and run a `gcloud` command manually.

**Comment by akshayshippy** [comment]
> We do not currently support Cloud Functions gen2. If you need support for gen2, you can use the `setup-gcloud` action and run a `gcloud` command manually.

@sethvargo I think most of us in this thread understand this is not currently supported and the possible alternative(s). I think we'd more like to know if this would be available in the near future vs. later (next weeks vs. months/years), so we can accordingly plan to rewrite our pipelines or simply hold off until the feature becomes available within github actions itself.

**Comment by mymyparty** [comment]
If you are interested in Cloud Functions gen 2 and perhaps you write in Go,
then it is ok to configure following Github Actions:
- Google Cloud Platform Auth (workload identity provider)
- Set up Cloud SDK (gcloud cli)

and your deployment command might look like
`gcloud functions deploy my-cloud-function --gen2 --runtime=go119 --region=us-central1 --source=.`

having configured alternatives, i could say that options above are much easier to configure than others.

**Comment by diervo** [comment]
2gen is no longer beta yes? :)

**Comment by mymyparty** [comment]
yes, they are good for production now.

**Comment by maxpain** [comment]
Any news?

**Comment by mymyparty** [comment]
@maxpain i would suggest you use `gcloud` tool and a little bit of custom steps in GitHub Actions pipelines. It is pretty easy and works well for awhile.

**Comment by vyshkov** [comment]
I made its working by using `gcloud`

Here is an example:

```
    steps:
    - uses: actions/checkout@v3
    - run: ls
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/idpool/providers/idprovider'
        service_account: ${{ vars.GCP_GITHUB_SERVICE_ACCOUNT }}
        token_format: 'access_token'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: 'Use to deploy a cloud function gen 2'
      run: 'gcloud functions deploy httptest1 --gen2 --runtime=nodejs18 --region=us-central1 --source=backend/service-secured-test --trigger-http --allow-unauthenticated --entry-point=helloHttp --memory=256MB --timeout=60s'


```

**Comment by hakontro** [comment]
@sethvargo @bharathkkb are you planning to add support for this in the (near) future?

**Comment by sydney-sisco** [comment]
So I have to use a workaround to deploy a gen2 function? It shouldn't be this hard to add CD to a cloud function.

**Comment by mymyparty** [comment]
above you can find solutions for Golang and Node, nothing difficult to use that other runtimes.

**Comment by danialdezfouli** [comment]
> I made it working by using `gcloud`
can we still have the curl for testing the output URL?
@vyshkov

**Comment by Wazbat** [comment]
> > I made it working by using `gcloud`
> 
> can we still have the curl for testing the output URL?

It's not pretty, but you should be able to get the URL via the `gcloud functions describe` utility

For example
```yaml
- nam: Get url
  id: get-url
  run: echo "url=$(gcloud functions describe function-name-here --gen2 --region europe-west2 --format json | jq .url -r)" >> $GITHUB_OUTPUT
```

The above step will store the url of the function under "url"
```
${{ steps.get-url.outputs.url }}
```
