### ISSUE TITLE
Timeout while deploying

### ISSUE THREAD

**Issue by ngmiduc** [google-github-actions/deploy-cloud-functions#333]
### TL;DR

Hi, 

I am not sure what I am doing wrong, 
but I am getting a timeout while deploying.

It seems to run but it takes a very long time until it timeouts.

You can find the infos below.

### Expected behavior

Should complete deployment

### Observed behavior

Returned error

### Action YAML

```yaml
name: ...

on:
  push:
    paths: ...
    branches: ...
    
jobs:
  jobid:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: <name of existing cloud function in GCP>
          runtime: python38
          entry_point: main (function is called like that in pythonfile.py>
          memory_mb: 256MB
          region: ...
          env_vars: ENV1=1,ENV2=2
          source_dir: subfolder/subsubfolder
          project_id: ...
          description: ....
          build_environment_variables: GOOGLE_FUNCTION_SOURCE=pythonfile.py
          secret_environment_variables: SECRET=projects/.../secret:latest
          min_instances: 0
          max_instances: 1
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/.../topics/topicId
          event_trigger_service: pubsub.googleapis.com
          deploy_timeout: 500

```
```


### Log output

```text
Creating new Cloud Function revision
Deploying Cloud Function
Still deploying Cloud Function (1/n)
Still deploying Cloud Function (2/n)
Still deploying Cloud Function (3/n)
Still deploying Cloud Function (4/n)
Still deploying Cloud Function (5/n)
Still deploying Cloud Function (6/n)
Still deploying Cloud Function (7/n)
Still deploying Cloud Function (8/n)
Still deploying Cloud Function (9/n)
Still deploying Cloud Function (10/n)
Still deploying Cloud Function (11/n)
Still deploying Cloud Function (12/n)
...
Still deploying Cloud Function (59/n)
Error: google-github-actions/deploy-cloud-functions failed with: operation timed out
```
```


### Additional information

_No response_
