### ISSUE TITLE
Support for Google Cloud Source Repository as source for the function or allow empty source_dir

### ISSUE THREAD

**Issue by Doggie52** [google-github-actions/deploy-cloud-functions#35]
### TL;DR

It's not possible to leave `source_dir` empty and just use the existing source directory that is set on the function currently. If `source_dir` is left empty, I get an error message on the GCF side:

```
FileNotFoundError: [Errno 2] No such file or directory: '/user_code/main.py'
```

If I pass the actual path to the repository, I get the following error message in my GitHub Action:

```
Unable to find https://source.developers.google.com/projects/xxx/repos/github_xxx/moveable-aliases/master/paths/
```

My current yaml looks like this:

```yaml
name: Deploy to GCF (dev)
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.actor == 'xxx' && github.ref == 'refs/heads/master'

    steps:
      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: xxx
          entry_point: xxx
          memory_mb: 512
          timeout: 540

          source_dir: https://source.developers.google.com/projects/xxx/repos/github_xxx/moveable-aliases/master/paths/
          region: europe-west2
          runtime: python37
          credentials: ${{ secrets.GCLOUD_CREDENTIALS }}
```

### Design

It would be nice to be able to leave this parameter empty. Or, if you are able to figure out why I can't seem to get this to work, it would be much appreciated.
