### ISSUE TITLE
Error: google-github-actions/deploy-cloud-functions failed with: operation failed: Build failed:

### ISSUE THREAD

**Issue by mpapec** [google-github-actions/deploy-cloud-functions#352]
### TL;DR

Execution fails with ```Error: google-github-actions/deploy-cloud-functions failed with: operation failed: Build failed: npm WARN deprecated urix@0.1.0:```

### Expected behavior

Not to fail.

### Observed behavior

It errored.

### Action YAML

```yaml
name: Devops GAE Deployment
on:
  push:
    branches:
      - devops
  workflow_dispatch:
    inputs:
      merged:
        description: 'Simulate git merge event'
        required: false
        default: true
        type: boolean
        
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         ref: devops
         
      - name: Joys of escaping shell parameters
        run: echo "SAUSAGE=NODE_ENV=${{ secrets.STAGING_NODE_ENV }}~BSV_NETWORK=testnet~TAAL_TESTNET_API_KEY=${{ secrets.STAGING_TAAL_TESTNET_API_KEY }}~MINIMUM_ACCEPTABLE_FEE=${{ secrets.STAGING_MINIMUM_ACCEPTABLE_FEE }}~DOJO_URL=${{ secrets.STAGING_DOJO_URL }}~KNEX_DB_CONNECTION=${{ secrets.STAGING_KNEX_DB_CONNECTION }}~KNEX_DB_CLIENT=${{ secrets.STAGING_KNEX_DB_CLIENT }}~MIGRATE_KEY=${{ secrets.STAGING_MIGRATE_KEY }}~ALLOWED_PAYMAIL_DOMAINS=${{ secrets.STAGING_ALLOWED_PAYMAIL_DOMAINS }}~PRIMARY_PAYMAIL_DOMAIN=${{ secrets.STAGING_PRIMARY_PAYMAIL_DOMAIN }}~SERVER_PRIVATE_KEY=${{ secrets.STAGING_SERVER_PRIVATE_KEY }}~CWI_NPM_TOKEN=${{ secrets.CWI_NPM_TOKEN }}" | sed ':a;N;$!ba; s/\n/\\\n/g' | sed 's/,/\\,/g' | sed 's/~/,/g' >> $GITHUB_ENV
      - name: Test set output
        run: echo $SAUSAGE        
        
      - uses: google-github-actions/deploy-cloud-functions@v0
        with:
          credentials: ${{ secrets.gcp_credentials }}
          # Runtime to use for the function
          runtime: "nodejs16"          
          # Name of the Cloud Function, same as the entry point name
          name: "myEnv"
          env_vars: ${{ env.SAUSAGE }}
      - uses: google-github-actions/deploy-appengine@v0
        with:
          credentials: ${{ secrets.gcp_credentials }}
          deliverables: app.devops.yaml
```

### Log output

```text
Error: google-github-actions/deploy-cloud-functions failed with: operation failed: Build failed: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     /www-data-home/.npm/_logs/2022-07-30T10_10_14_016Z-debug-0.log; Error ID: beaf8772
```
