### ISSUE TITLE
.gcloudignore is not recognized.

### ISSUE THREAD

**Issue by miya** [google-github-actions/deploy-cloud-functions#36]
### TL;DR

.gcloudignore is not recognized.

**Expected behavior**

I believe that the files written in .gcloudignore are not to be deployed to cloud functions.

**Observed behavior**

When I deployed using deploy-cloud-functions, files that should have been written in .gcloudignore were also deployed.This was confirmed by downloading the zip file of the source code from cloud-functions on the web.

### Reproduction

**Action YAML**

```yaml
name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
        with:
          name: notice-seat-availability
          runtime: python38
          credentials: ${{ secrets.gcp_credentials }}
          entry_point: run
          region: asia-northeast1
          source_dir: .        
          env_vars: LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
```

**Repository**

https://github.com/akishima-ensis/notice-seat-availability

**Comment by bharathkkb** [comment]
Thanks for the report @miya. I'll look into how we can add this feature

**Comment by miya** [comment]
Thank you! I'm sorry I can't help you!

**Comment by SkYNewZ** [comment]
Any news about this ?

**Comment by sfyfedotcom** [comment]
Would be nice if this was built in, but this works for me, for now:
```
- run: xargs rm -rf < .gcloudignore
```

**Comment by RickRen7575** [comment]
@sfyfedotcom do you just run this before anything else?

**Comment by sfyfedotcom** [comment]
> @sfyfedotcom do you just run this before anything else?

```
name: Run tests and deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: xargs rm -rf < .gcloudignore
    - name: Deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        …
```
