### ISSUE TITLE
Error: Unable to find source_dir 

### ISSUE THREAD

**Issue by Rahulsharma0810** [google-github-actions/deploy-cloud-functions#37]
I am trying to get source_dir value working, here is my code structure.

```
├── .github
│   └── workflows
│       └── main.yml
├── .gitignore
├── LICENSE
├── README.md
└── src
    ├── main.py
    └── requirements.txt
```

```
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - id: Deploy

      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: RvsAirtable
        runtime: python38
        source_dir: src
```

![image](https://user-images.githubusercontent.com/9934859/107003067-32db3b00-67b2-11eb-8111-012493611817.png)

how does this variable work?

**Comment by bharathkkb** [comment]
Hi @Rahulsharma0810 
Looks like it was unable to find the `src` directory. I don't see a checkout step in your workflow, you will need use the checkout action to pull code into the runner.

```
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: Deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: RvsAirtable
        runtime: python38
        source_dir: src
```
