### ISSUE TITLE
Option to deploy multiple functions

### ISSUE THREAD

**Issue by harshitaXerox** [google-github-actions/deploy-cloud-functions#391]
### TL;DR

Do we have the option to deploy multiple functions using this action? If yes could you please let me know how...if not it would be great if you can add that  

### Detailed design

- id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'my-function1' , 'my-function2' 
        runtime: 'nodejs16'

**Comment by sethvargo** [comment]
Hi @harshitaXerox - you would specify the yaml block twice as different steps:

```yaml
- id: 'deploy1'
  uses: 'google-github-actions/deploy-cloud-functions@v1'
  with:
    name: 'my-function1'
    runtime: 'nodejs16'

- id: 'deploy2'
  uses: 'google-github-actions/deploy-cloud-functions@v1'
  with:
    name: 'my-function2'
    runtime: 'nodejs16'
```

You could also use a [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs). Depending on how you specify the job, it will either run in serial or parallel to the other deployment. This is not specific to the deploy-cloud-functions action. For more information, see the [GitHub Actions docs](https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow).
