### ISSUE TITLE
Option for allowing unauthenticated requests

### ISSUE THREAD

**Issue by aflmp** [google-github-actions/deploy-cloud-functions#399]
Hi there,
Is there an option for allowing unauthenticated requests to the cloud-function just like https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--[no-]allow-unauthenticated ? I'm only seeing authenticated requests being allowed right now, below is the config that i'm using
```
- id: deploy
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        name: some-function
        runtime: go121
```

**Comment by Kurtz1993** [comment]
@aflmp I think it that using the option:

`ingress_settings: ALLOW_ALL` will do that.

Try updating your settings as follows:

```yaml
- id: deploy
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        name: some-function
        runtime: go121
        ingress_settings: ALLOW_ALL
```
