### ISSUE TITLE
Timeout when adding `secret_environment_variables`

### ISSUE THREAD

**Issue by rikintanna** [google-github-actions/deploy-cloud-functions#407]
### TL;DR

When I attempt to add a secret env var to my deploy workflow, my deploy times out with no logs surfacing.

### Expected behavior

Deploy to Cloud Functions succeeds

### Observed behavior

Deploy to Cloud Functions times out

### Action YAML

```yaml
name: Production CI/CD

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Comma separated list of tags"
        required: false

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  deploy-to-firebase:
    runs-on: ubuntu-latest
    needs: unit-tests
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.GCP_SA_KEY }}"
          projectId: ...
          channelId: live

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: [unit-tests, deploy-to-firebase]
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to Google Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: api
          runtime: nodejs18
          project_id: ...
          entry_point: api
          ingress_settings: ALLOW_ALL
          env_vars: DB=(default)
          secret_environment_variables: API_KEYS=projects/.../secrets/API_KEYS
          timeout: 300
```

### Log output

```
Run google-github-actions/deploy-cloud-functions@v2
Created zip file from './' at '/tmp/cfsrc-28b9924ab371d3f86c84f5bd.zip'
Creating new Cloud Function revision
Deploying Cloud Function
Still deploying Cloud Function (1/n)
Still deploying Cloud Function (2/n)
Still deploying Cloud Function (3/n)
Still deploying Cloud Function (4/n)
Still deploying Cloud Function (5/n)
Still deploying Cloud Function (6/n)
Still deploying Cloud Function (7/n)
Still deploying Cloud Function (8/n)
Still deploying Cloud Function (9/n)
Still deploying Cloud Function (10/n)
Still deploying Cloud Function (11/n)
Still deploying Cloud Function (12/n)
Still deploying Cloud Function (13/n)
Still deploying Cloud Function (14/n)
Still deploying Cloud Function (15/n)
Still deploying Cloud Function (16/n)
Still deploying Cloud Function (17/n)
Still deploying Cloud Function (18/n)
Still deploying Cloud Function (19/n)
Still deploying Cloud Function (20/n)
Still deploying Cloud Function (21/n)
Still deploying Cloud Function (22/n)
Still deploying Cloud Function (23/n)
Still deploying Cloud Function (24/n)
Still deploying Cloud Function (25/n)
Still deploying Cloud Function (26/n)
Still deploying Cloud Function (27/n)
Still deploying Cloud Function (28/n)
Still deploying Cloud Function (29/n)
Still deploying Cloud Function (30/n)
Still deploying Cloud Function (31/n)
Still deploying Cloud Function (32/n)
Still deploying Cloud Function (33/n)
Still deploying Cloud Function (34/n)
Still deploying Cloud Function (35/n)
Still deploying Cloud Function (36/n)
Still deploying Cloud Function (37/n)
Still deploying Cloud Function (38/n)
Still deploying Cloud Function (39/n)
Still deploying Cloud Function (40/n)
Still deploying Cloud Function (41/n)
Still deploying Cloud Function (42/n)
Still deploying Cloud Function (43/n)
Still deploying Cloud Function (44/n)
Still deploying Cloud Function (45/n)
Still deploying Cloud Function (46/n)
Still deploying Cloud Function (47/n)
Still deploying Cloud Function (48/n)
Still deploying Cloud Function (49/n)
Still deploying Cloud Function (50/n)
Still deploying Cloud Function (51/n)
Still deploying Cloud Function (52/n)
Still deploying Cloud Function (53/n)
Still deploying Cloud Function (54/n)
Still deploying Cloud Function (55/n)
Still deploying Cloud Function (56/n)
Still deploying Cloud Function (57/n)
Still deploying Cloud Function (58/n)
Still deploying Cloud Function (59/n)
Error: google-github-actions/deploy-cloud-functions failed with: operation timed out
```

### Additional information

similar to https://github.com/google-github-actions/deploy-cloud-functions/issues/333

but i've confirmed my syntax is correct
