### ISSUE TITLE
Deploy uploads corrupt zip

### ISSUE THREAD

**Issue by brianzinn** [google-github-actions/deploy-cloud-functions#41]
### TL;DR
The action appears to not fully upload the zip (it's a corrupt zip - manually extracting gives errors.  Viewing the function provides a link to the build errors.

**Expected behavior**
Function should deploy without errors.

**Observed behavior**
This fails 3 times and the build fails:
```bash
End-of-central-directory signature not found. Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive. In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
```

Downloading the .zip file from the function in console there are errors unzipping locally.

### Reproduction

**Action YAML**
Due to security and repeatability - we only reference versioned external actions.  Assuming that is the same as `@main`.
```yaml
       - id: actual-deploy
         uses: google-github-actions/deploy-cloud-functions@v0.2.0
         with:
           name: <redacted>
           runtime: nodejs10
           credentials: ${{ secrets.GCP_SA_KEY }}
           entry_point: <redacted>
           timeout: 240
```

This is a fully working YAML
```yaml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install build
        run: |
          yarn install
          yarn build
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy Function <redacted>
        run: gcloud functions deploy <redacted> --runtime nodejs10 --trigger-http  --entry-point <redacted> --timeout 240 --set-env-vars CLOUD_SQL_CONNECTION_NAME=${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
  
```

**Additional information**
Nothing atypical.  It works with regular gcloud command.
