### ISSUE TITLE
Invalid Request. Violations: Event triggered 1st Gen function should have trigger resource set.

### ISSUE THREAD

**Issue by huy-trinh-pionero** [google-github-actions/deploy-cloud-functions#425]
### TL;DR

I try to deploy cloud function (gen1, because gen2 does not support trigger firebase auth) but It always response an error 
```
Error: google-github-actions/deploy-cloud-functions failed with: failed to POST https://cloudfunctions.googleapis.com/v2/projects/pds-system-dev/locations/us-central1/functions?functionId=createUserHook: (400) {
  "error": {
    "code": 400,
    "message": "Invalid Request. Violations: Event triggered 1st Gen function should have trigger resource set.",
    "status": "INVALID_ARGUMENT"
  }
}
```
I don't know what resource is mentioned here, and how to push it in .yaml file 

### Action YAML

```yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    name: Deploy Function
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: (Dev) Authenticate the action
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON_ONELINE }}

      - name: (Dev) Deploy firebase function
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        timeout-minutes: 10
        with:
          name: 'createUserHook'
          runtime: 'nodejs20'
          environment: GEN_1
          memory: '128M'
          source_dir: './functions'
          event_trigger_type: 'providers/firebase.auth/eventTypes/user.create'
```
