### ISSUE TITLE
Docker regisrty not working for Artifact registry in v2

### ISSUE THREAD

**Issue by gauraw10** [google-github-actions/deploy-cloud-functions#451]
### TL;DR

- There is no README document for this input [docker_registry](https://github.com/google-github-actions/deploy-cloud-functions/blob/release/v2/src/main.ts#L76) in v2
- When I am using a artifact registry like `europe-west1-docker.pkg.dev` it converts to `EUROPE_WEST1_DOCKER.PKG.DEV ` because of this [code](https://github.com/google-github-actions/deploy-cloud-functions/blob/release/v2/src/util.ts#L131) and we get the error:

```json
"error": {
    "code": 400,
    "message": "Invalid value at 'function.docker_registry' (type.googleapis.com/google.cloud.functions.v1.CloudFunction.DockerRegistry), \"EUROPE_WEST1_DOCKER.PKG.DEV\"",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "function.docker_registry",
            "description": "Invalid value at 'function.docker_registry' (type.googleapis.com/google.cloud.functions.v1.CloudFunction.DockerRegistry), \"EUROPE_WEST1_DOCKER.PKG.DEV\""
          } 
```

### Expected behavior

It must be passed and the function should be mapped to the `artifact registry` image (after the build).

### Observed behavior

- Failed because of the code issue and got 400 response code

### Action YAML

```yaml
- id: deploy
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: "test-function"
          description: "test"
          runtime: "go122"
          project_id: "test-project"
          region: "europe-west1"
          memory_mb: "256"
          timeout: "540"
          source_dir: "src/"
          entry_point: "test-function"
          service_account_email: email@email.com
          docker_registry: europe-west1-docker.pkg.dev
```

### Log output

```text
"error": {
    "code": 400,
    "message": "Invalid value at 'function.docker_registry' (type.googleapis.com/google.cloud.functions.v1.CloudFunction.DockerRegistry), \"EUROPE_WEST1_DOCKER.PKG.DEV\"",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "function.docker_registry",
            "description": "Invalid value at 'function.docker_registry' (type.googleapis.com/google.cloud.functions.v1.CloudFunction.DockerRegistry), \"EUROPE_WEST1_DOCKER.PKG.DEV\""
          }
```
