### ISSUE TITLE
Error: The request has errors (PubSub Topic triggers)

### ISSUE THREAD

**Issue by mattes** [google-github-actions/deploy-cloud-functions#47]
<img width="580" alt="Screen Shot 2021-02-20 at 9 28 19 PM" src="https://user-images.githubusercontent.com/1240531/108616496-a0968200-73c2-11eb-91a4-869374dabf5c.png">

I believe I included all required fields. 

Cloud Functions API is enabled and the calling credentials have the `Cloud Functions Admin` and `Service Account User` role.

**Comment by mattes** [comment]
From the Logs:
(I replaced sensitive data with `xxx`)

```
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {
      "code": 3,
      "message": "The request has errors"
    },
    "authenticationInfo": {
      "principalEmail": "xxx",
      "serviceAccountKeyName": "xxx"
    },
    "requestMetadata": {
      "callerIp": "xxx",
      "callerSuppliedUserAgent": "github-actions-deploy-cloud-functions/0.1.0 google-api-nodejs-client/4.4.1 (gzip),gzip(gfe),gzip(gfe)",
      "requestAttributes": {
        "time": "2021-02-21T05:23:31.950936Z",
        "auth": {}
      },
      "destinationAttributes": {}
    },
    "serviceName": "cloudfunctions.googleapis.com",
    "methodName": "google.cloud.functions.v1.CloudFunctionsService.UpdateFunction",
    "authorizationInfo": [
      {
        "resource": "xxx",
        "permission": "cloudfunctions.functions.update",
        "granted": true,
        "resourceAttributes": {}
      }
    ],
    "resourceName": "xxx",
    "request": {
      "function": {
        "name": "xxx",
        "httpsTrigger": {},
        "entryPoint": "Run",
        "sourceUploadUrl": "xxx",
        "runtime": "go113"
      },
      "updateMask": "sourceUploadUrl,name,environmentVariables,entryPoint,runtime,vpcConnector,serviceAccountEmail,timeout,maxInstances,eventTrigger.eventType,eventTrigger.resource,eventTrigger.service",
      "@type": "type.googleapis.com/google.cloud.functions.v1.UpdateFunctionRequest"
    },
    "resourceLocation": {
      "currentLocations": [
        "us-central1"
      ]
    }
  },
  "insertId": "xxx",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "us-central1",
      "project_id": "xxx",
      "function_name": "xxx"
    }
  },
  "timestamp": "2021-02-21T05:23:31.917344Z",
  "severity": "ERROR",
  "logName": "projects/xxx/logs/cloudaudit.googleapis.com%2Factivity",
  "receiveTimestamp": "2021-02-21T05:23:32.237789442Z"
}
```

**Comment by bharathkkb** [comment]
Thanks for the report @mattes 
If the repo where this occurred is public, could you link it? It would be helpful for repro

**Comment by mattes** [comment]
The repo isn't public unfortunately. 

Using `gcloud` I'm able to successfully deploy:

```
	gcloud functions deploy xxx \
		--entry-point Run \
		--runtime go113 \
		--source functions/my-function1 \
		--trigger-topic xxx \
		--project xxx
```

**Comment by mattes** [comment]
The difference appears to be `--trigger-topic xxx` from the `gcloud` command. 

Looking at the [API docs](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#CloudFunction), I was able to get my function deployed with:

```
    - name: Deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        region: us-central1
        name: xxx
        runtime: go113
        entry_point: Run
        source_dir: functions/my-function1
        event_trigger_type: google.pubsub.topic.publish
        event_trigger_resource: projects/xxx/topics/xxx
        event_trigger_service: pubsub.googleapis.com
        credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
```

User error, sorry. :-)
