### ISSUE TITLE
Action fails even though gcloud equivalent succeeds

### ISSUE THREAD

**Issue by snoozesecurity** [google-github-actions/deploy-cloud-functions#55]
### TL;DR
I get the following message which isn't overly helpful:
Error: The request has errors

**Observed behavior**

```
Run google-github-actions/deploy-cloud-functions@main
  with:
    credentials: ***
  
    name: function-name
    runtime: python38
    region: us-west2
Setting project Id from credentials
zip file /tmp/cfsrc-99289.zip created successfully
function source zipfile created: 22486 bytes
zip file /tmp/cfsrc-99289.zip uploaded successfully
Creating a function revision
Error: The request has errors
```

### Reproduction

**Action YAML**

```yaml
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        name: function-name
        runtime: python38
        region: us-west2
```

In searching through GCP logs I found this, not sure if something is parsing serviceAccountKeyName improperly??

```
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {
      "code": 3,
      "message": "The request has errors"
    },
    "authenticationInfo": {
      "principalEmail": "REDACTED@project.iam.gserviceaccount.com",
      "serviceAccountKeyName": "//iam.googleapis.com/projects/REDACTED/serviceAccounts/REDACTED@REDACTED.iam.gserviceaccount.com/keys/REDACTED"
    }
```

**Comment by bharathkkb** [comment]
Hi @snoozesecurity, thanks for the report. 

The auth does look okay, principal is your SA email and sa keyname is of the form `//iam.googleapis.com/projects/PROJECT_ID/serviceAccounts/SA_EMAIL/keys/KEY_ID`

You mentioned it works fine with gcloud locally can you paste the gcloud command? Also is this a public repo I can take a look at - that could help with a reproduction

**Comment by ajmdot** [comment]
I am experiencing the same issue. Gcloud command works but not this action same error message as well at the same step.

**Comment by ichengchang** [comment]
I am also having the same issue when trying to deploy `java11` function. Here's the full log with sensitive data redacted.

 `{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {
      "code": 3,
      "message": "The request has errors"
    },
    "authenticationInfo": {
      "principalEmail": "SA_EMAIL@PROJECT_ID.iam.gserviceaccount.com",
      "serviceAccountKeyName": "//iam.googleapis.com/projects/PROJECT_ID/serviceAccounts/SA_EMAIL@PROJECT_ID.iam.gserviceaccount.com/keys/7d09-----------------------------------"
    },
    "requestMetadata": {
      "callerIp": "xxx.xxx.xxx.xxx",
      "callerSuppliedUserAgent": "github-actions-deploy-cloud-functions/0.1.0 google-api-nodejs-client/4.4.1 (gzip),gzip(gfe),gzip(gfe)",
      "requestAttributes": {
        "time": "2021-06-02T12:20:31.967506Z",
        "auth": {}
      },
      "destinationAttributes": {}
    },
    "serviceName": "cloudfunctions.googleapis.com",
    "methodName": "google.cloud.functions.v1.CloudFunctionsService.UpdateFunction",
    "authorizationInfo": [
      {
        "resource": "projects/PROJECT_ID/locations/us-central1/functions/my-function",
        "permission": "cloudfunctions.functions.update",
        "granted": true,
        "resourceAttributes": {}
      }
    ],
    "resourceName": "projects/PROJECT_ID/locations/us-central1/functions/my-function",
    "request": {
      "updateMask": "sourceUploadUrl,name,environmentVariables,entryPoint,runtime,vpcConnector,serviceAccountEmail,timeout,maxInstances,eventTrigger.eventType,eventTrigger.resource,eventTrigger.service,labels",
      "function": {
        "entryPoint": "cloudfunctions.MyFunction",
        "runtime": "java11",
        "eventTrigger": {
          "resource": "projects/_/buckets/MY_BUCKET/objects/*",
          "eventType": "providers/cloud.storage/eventTypes/object.finalize",
          "service": ""
        },
        "name": "projects/PROJECT_ID/locations/us-central1/functions/my-function",
        "sourceUploadUrl": "https://storage.googleapis.com/gcf-upload-us-central1-xxxxxxx.zip?GoogleAccessId=service-xxxxxxxxxx@gcf-admin-robot.iam.gserviceaccount.com&Expires=1622638231&Signature=xxxxxxxxxxxxxxxxxxxxxxxx"
      },
      "@type": "type.googleapis.com/google.cloud.functions.v1.UpdateFunctionRequest"
    },
    "resourceLocation": {
      "currentLocations": [
        "us-central1"
      ]
    }
  },
  "insertId": "totibnexsaxx",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "PROJECT_ID",
      "region": "us-central1",
      "function_name": "my-function"
    }
  },
  "timestamp": "2021-06-02T12:20:31.934867Z",
  "severity": "ERROR",
  "logName": "projects/PROJECT_ID/logs/cloudaudit.googleapis.com%2Factivity",
  "receiveTimestamp": "2021-06-02T12:20:32.904893451Z"
}`

**Comment by jackstruck** [comment]
Looks like this error can be thrown for a variety of reasons: https://stackoverflow.com/questions/46818082/error-http-error-400-the-request-has-errors-firebase-firestore-cloud-function and I suspect that we are seeing this here but not on the gcloud command line because of a mis-configuration of the action setup in the .yml file

Unfortunately, we can't pass the debug flag into the deployment here:
`Warning: Unexpected input(s) 'debug', valid inputs are ['credentials', 'name', 'description', 'project_id', 'region', 'source_dir', 'env_vars', 'entry_point', 'runtime', 'vpc_connector', 'service_account_email', 'timeout', 'max_instances', 'event_trigger_type', 'event_trigger_resource', 'event_trigger_service']`

Maybe this should be added as a feature?

**Comment by bharathkkb** [comment]
@jackstruck @ichengchang 
If you repo is public it would help with a repro, I do suspect this maybe a bug when we call the `CloudFunctionsService.UpdateFunction` with certain parameters.

**Comment by jackstruck** [comment]
@bharathkkb The repo is not public but the workflow code is pretty simple:
name: Pylint

```
on:
  push:
    branches:
      - main
    paths:
      - REDACTED/**

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: Deploy
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          credentials: ${{ secrets.REDACTED }}
          name: REDACTED
          runtime: python39
          region: us-east4
          source_dir: REDACTED
```

**Comment by jackstruck** [comment]
@bharathkkb Any update on whether this is a bug or user error? Also any workarounds to get a better description of what's going wrong in case it's the latter?

**Comment by ankile** [comment]
Having the same issue. I have two functions that I want to deploy using Github actions. The first is a pubsub-function and deploys just fine, while the second one is a storage-activated function which crashes with the error: `Error: The request has errors`. My workflow yaml is below:

```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - id: deploy_run_screen
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: run-screen
          runtime: python39
          credentials: ${{ secrets.gcp_credentials }}
          region: europe-west1
          entry_point: run_screen
          source_dir: src/generate_scores
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/<project_name>/topics/<topic_name>

  build-2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - id: deploy_run_screen_storage
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: run-screen-storage
          runtime: python39
          credentials: ${{ secrets.gcp_credentials }}
          region: europe-west1
          entry_point: run_screen_from_storage
          source_dir: src/generate_scores_storage
          event_trigger_type: google.storage.object.finalize
          event_trigger_resource: <bucket_name>
```

Please, any help would be immensely helpful and appreciated. Thanks :)
