### ISSUE TITLE
Merge `envVars` and `envVarsFile` if both are set

### ISSUE THREAD

**Issue by peterj** [google-github-actions/deploy-cloud-functions#57]
I have a scenario I store secrets in Github (e.g. PASSWORD, API_KEY), while I also have some non-secret environment variables I'd like to set per environment (e.g. `prod.yaml` and `staging.yaml`).

I have two separate workflows - one for Staging and one for Production where I am referring to the Github secrets. For example:

```yaml
    with:
          name: my-func
          runtime: nodejs12
          entry_point: index
          source_dir: ./functions/build/src
          env_vars: PASSWORD=${{ secrets.PASSWORD }},API_KEY=${{ secrets.API_KEY }}
```

Since I can't mix and match `env_vars` and `env_vars_file`, I'd probably have to combine the variables from secrets and the file and then pass them in either as a file or separately.

It would be useful if there was an option that allows us to set both `env_vars` and `env_vars_file` and merge the values [here]( https://github.com/google-github-actions/deploy-cloud-functions/blob/b1ed2309dc78c032f513563fe1eedce3d47beb5b/src/cloudFunction.ts#L114). 

In a case where a secret would overwrite the value in an env file (or vice-versa), the action would throw an exception.
