### ISSUE TITLE
Could you improve the documentation of the trigger inputs please? (especially pubsub)

### ISSUE THREAD

**Issue by erzz** [google-github-actions/deploy-cloud-functions#58]
### Question

As an example - I am trying to implement the equivalent of gcloud command

```
gcloud functions deploy my-function \
  --runtime go113  \
  --trigger-topic=some_topic \
  --service-account=$CLOUD_FUNCTION_SA_EMAIL \
  --project $PROJECT_ID \
  --entry-point MyEntrypoint \
  --set-env-vars PROJECT_ID=$PROJECT_ID,REPLAY_TOPIC_ID=$REPLAY_TOPIC_ID,BUCKET_NAME=$BUCKET_NAME  \
  --region $REGION \
  --memory 256 \
  --timeout 60 \
  --max-instances 100 \
  --quiet
```

Documentation issues:

> event_trigger_type: (Optional) Specifies which action should trigger the function. Defaults to creation of http trigger.

OK, so what are the other trigger types? There is not a direct mapping of gcloud flag to action input here so its pure guesswork. What should I use for the equivalent of `--trigger-topic=some_topic` ?

I crawled around your issues until I found a maybe solution of :

```
event_trigger_type: google.pubsub.topic.publish
event_trigger_resource: projects/$PROJECT_ID/topics/$PDH_TOPIC_ID
event_trigger_service: pubsub.googleapis.com
```

This worked it seemed - but as these seem to be legacy flags - I am not sure for how long or if there is a simpler / shorter set of values that could be used

**Comment by RickRen7575** [comment]
I also am looking for this too^ thank you!

**Comment by RickRen7575** [comment]
Along this topic - I also figured out how to do it for storage if anyone is wondering:

`
event_trigger_type: google.storage.object.finalize
event_trigger_resource: projects/PROJECT/buckets/BUCKET
event_trigger_service: storage.googleapis.com
`

**Comment by bharathkkb** [comment]
Thanks for the report @erzz  @RickRen7575

While the [API](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#EventTrigger) still requires these in the above format, we can handle that inside the action by detecting event types.

**Comment by PeaceS** [comment]
This helps A LOT!!

**Comment by ankile** [comment]
> Along this topic - I also figured out how to do it for storage if anyone is wondering:
> 
> ```
> event_trigger_type: google.storage.object.finalize
> event_trigger_resource: projects/PROJECT/buckets/BUCKET
> event_trigger_service: storage.googleapis.com
> ```

Thank you @RickRen7575 this literally saved my life. <3 This definitely needs to be better documented!

**Comment by erzz** [comment]
I feel this needs a bump after the best part of a year :)  Still today I am crawling the web and the source to try and find clues for implementing the various kinds of triggers!

**Comment by JaredEzz** [comment]
Agreed. Trying to setup a workflow for deploying a function triggered by pub/sub is not well documented.

The previously mentioned solution
```
event_trigger_type: google.pubsub.topic.publish
event_trigger_resource: projects/$PROJECT_ID/topics/$TOPIC_ID
event_trigger_service: pubsub.googleapis.com
```


may work but those values are not easy to find

**Comment by gregorvand** [comment]
Google are you kidding? 

Why is this do badly documented?

**Comment by ankile** [comment]
Yes, it’s incredible..

**Comment by gregorvand** [comment]
To help anyone also getting stuck - 

```
- id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          # Name of the Cloud Function, same as the entry point name
          name: "${FUNCTION_NAME}"
          region: "asia-southeast1" // optional change of region
          # Runtime to use for the function
          runtime: "nodejs16"
                    event_trigger_type: "google.pubsub.topic.publish"
                    event_trigger_resource: "projects/${PROJECT_VALUE}/topics/${TOPIC_ID}" // ie the string identifying the topic, not anything else
                    event_trigger_service: "pubsub.googleapis.com"
```

Also, if you have deployed an `http` based trigger with the same function name - delete that first, as a trigger-based function with the same name will not deploy otherwise
