### ISSUE TITLE
How can I deploy all my functions?

### ISSUE THREAD

**Issue by nilsreichardt** [google-github-actions/deploy-cloud-functions#61]
### Question
You have to pass the parameter `name`. This is the name of a Cloud Function. But I don't want to deploy 1 Cloud Function, I want to deploy all my functions. How can I do this?

**Comment by ozburo** [comment]
Create an action for each of your functions, if want the same function in a different region, create another action for that one as well...

**Comment by nilsreichardt** [comment]
This is a horrible design. When a developer writes a cloud_function, the developer would also have to change the GitHub Actions. This can be forgotten very easily. And there would be not error messages.

**Comment by bharathkkb** [comment]
Hi @nilsreichardt

IIUC you have a collection of functions you would like to deploy using this action. You can use [a build matrix](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix) along with this action to express this succinctly.

**Comment by nilsreichardt** [comment]
Hi @bharathkkb, thanks for you reply! But then I still would need to update my code on two places, when I add a function 😔 So there is nothing like `firebase deploy` which deploys all functions located in the `src` folder, right?

**Comment by bharathkkb** [comment]
While we dont have any plans to add this right now, I have a possible workaround. If all your function paths are well defined say `repo-root/functions/fn-1,repo-root/functions/fn-2 etc` etc, you can build the matrix dynamically -  use one job to list all dirs under `repo-root/functions`, output that and read it in a second job as a matrix. [example](https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/#:~:text=new%20fromjson()%20method%20in%20expressions) Does that help?

**Comment by nilsreichardt** [comment]
Thanks for your suggestion! However, I wrote my own workaround:

My workflow:
```yaml
name: typescript-cloud-functions

on:
  push:
    branches:
      - master
    paths:
      - 'typescript_cloud_functions/**'

jobs:
  deploy-dev-typescript-cloud-functions:
    runs-on: ubuntu-latest
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_FIREBASE_CLOUD_FUNCTIONS_DEV_KEY }}
    steps:
    - uses: actions/checkout@v2
    - run: ./.github/workflows/scripts/deploy_typescript_cloud_functions.sh dev

  deploy-prod-typescript-cloud-functions:
    runs-on: ubuntu-latest
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_FIREBASE_CLOUD_FUNCTIONS_PROD_KEY }}
    steps:
    - uses: actions/checkout@v2
    - run: ./.github/workflows/scripts/deploy_typescript_cloud_functions.sh prod
```

My `deploy_typescript_cloud_functions.sh`
```sh
#!/bin/bash

# How to fix "Permissions denied" error when running this script:
# Run locally "chmod +x FILENAME.sh" and commit

FLAVOR=$1 # [prod, dev]

echo "👉 Navigating to typescript_cloud_functions"
cd typescript_cloud_functions

echo "👉 Set Google Service Account as environment variable"
echo $GCP_SA_KEY > firebase-cli-service-account.json
export GOOGLE_APPLICATION_CREDENTIALS=firebase-cli-service-account.json

echo "👉 Installing Firebase CLI"
sudo npm i -g firebase-tools

echo "👉 Deploying typescript_cloud_functions"
# "firebase deploy" can not be used, because we have cloud functions written in
# Python and TypeScript. If we deploy the TypeScript cloud functions we get an
# error in the ci environment that there are cloud functions (the Python
# functions), which are in the (TypeScript) code.
#
# There is a PR for a flag "--ignore-existing-functions". Until this PR is
# merged, we have to use this workaround.
#
# PR: https://github.com/firebase/firebase-tools/pull/999
echo "n\n" | firebase deploy --only functions --interactive --project gatch-$FLAVOR
```

**Comment by ozburo** [comment]
I see what you did there - dropped down into bash xD

**Comment by bharathkkb** [comment]
@nilsreichardt awesome, closing this out since there are some workarounds

**Comment by jonathanlaniado** [comment]
@nilsreichardt, this is probably not the best way to do it, but here's how I was able to achieve this:

```
name: Deploy Cloud Functions

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs
        run: echo "::set-output name=dir::$(ls -d * | grep -v "archive" | jq -R -s -c 'split("\n")[:-1]')"
        
  loop:
    runs-on: ubuntu-latest
    needs: [directories]
    strategy:
      matrix:
        dir: ${{ fromJson(needs.directories.outputs.dir) }}
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: ${{ matrix.dir }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        runtime: python39
        source_dir: ${{ matrix.dir }}
```

The `directories` job gets all my root-level folders, each of which is another GCF. Under `loop`, I store my directories in a matrix and then deploy each one using Python 3.9.

This works for me, hopefully this helps someone out. If I can optimize this, let me know!
