### ISSUE TITLE
Error during the deployment but the GA pass

### ISSUE THREAD

**Issue by GerardPaligot** [google-github-actions/deploy-cloud-functions#71]
### TL;DR

When I'm trying to publish a cloud function trigger by HTTP request, the GitHub Actions pass but the cloud function isn't updated on GCP/FirebasE.

**Expected behavior**

If there is any error during the deployment, the GA shouldn't pass and give me information to know how to fix the deployment.

**Observed behavior**

Give this output in the log of the GitHub Action:

```
Function deployment updated
No URL set. Only HttpsTrigger Cloud Functions have URL.
```

### Reproduction

**Action YAML**

```yaml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-functions:
    runs-on: latest-ubuntu
    env:
      working-directory: ./functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
            node-version: '12'
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - run: npm i -g firebase-tools
      - run: yarn
        working-directory: ${{ env.working-directory }}
      - uses: google-github-actions/deploy-cloud-functions@v0.5.0
        with:
          name: api # here a cloud function trigger by a http request
          runtime: nodejs12
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - uses: google-github-actions/deploy-cloud-functions@v0.5.0
        with:
          name: uploadCourses # here a cloud function trigger by an event on Google Storage
          runtime: nodejs12
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}
```

**Additional information**

Maybe linked to https://github.com/google-github-actions/deploy-cloud-functions/issues/47?

It seems, there is an error in the archive uploaded on GCP.

<img width="1033" alt="Capture d’écran 2021-06-15 à 11 38 36" src="https://user-images.githubusercontent.com/1913901/122030628-3c168d00-cdce-11eb-8976-3471ff39c4ef.png">
