### ISSUE TITLE
Error deploying function - step freezes 

### ISSUE THREAD

**Issue by dahsser** [google-github-actions/deploy-cloud-functions#87]
### TL;DR
Getting timeout on deployment
**Expected behavior**
Function deployed

**Observed behavior**
Action hanged 1 hour before timeout, everything was working normal days ago, I had to use an older commit to deploy this function successfully.
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

[1924:0x345b0e0]  4663163 ms: Mark-sweep 2034.7 (2050.7) -> 2034.5 (2051.2) MB, 3339.9 / 0.1 ms  (average mu = 0.091, current mu = 0.001) allocation failure scavenge might not succeed
[1924:0x345b0e0]  4666496 ms: Mark-sweep 2035.3 (2051.2) -> 2035.3 (2052.0) MB, 3329.7 / 0.1 ms  (average mu = 0.047, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

 1: 0x9da7c0 node::Abort() [/home/runner/runners/2.278.0/externals/node12/bin/node]
 2: 0x9db976 node::OnFatalError(char const*, char const*) [/home/runner/runners/2.278.0/externals/node12/bin/node]
 3: 0xb39f1e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/runner/runners/2.278.0/externals/node12/bin/node]
 4: 0xb3a299 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/runner/runners/2.278.0/externals/node12/bin/node]
 5: 0xce5635  [/home/runner/runners/2.278.0/externals/node12/bin/node]
 6: 0xce5cc6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/home/runner/runners/2.278.0/externals/node12/bin/node]
 7: 0xcf1b5a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/runner/runners/2.278.0/externals/node12/bin/node]
 8: 0xcf2a65 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/runner/runners/2.278.0/externals/node12/bin/node]
 9: 0xcf5478 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/home/runner/runners/2.278.0/externals/node12/bin/node]
10: 0xcc30c6 v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [/home/runner/runners/2.278.0/externals/node12/bin/node]
11: 0xcc387d v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const> const&, v8::internal::AllocationType) [/home/runner/runners/2.278.0/externals/node12/bin/node]
12: 0xb5239f v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/home/runner/runners/2.278.0/externals/node12/bin/node]
13: 0xa93150 node::StringBytes::Encode(v8::Isolate*, char const*, node::encoding, v8::Local<v8::Value>*) [/home/runner/runners/2.278.0/externals/node12/bin/node]
14: 0x9e9d99 node::fs::AfterScanDirWithTypes(uv_fs_s*) [/home/runner/runners/2.278.0/externals/node12/bin/node]
15: 0x12d21f5  [/home/runner/runners/2.278.0/externals/node12/bin/node]
16: 0x12d66e1  [/home/runner/runners/2.278.0/externals/node12/bin/node]
17: 0x12e8ce8  [/home/runner/runners/2.278.0/externals/node12/bin/node]
18: 0x12d706b uv_run [/home/runner/runners/2.278.0/externals/node12/bin/node]
19: 0xa1c9b7 node::NodeMainInstance::Run() [/home/runner/runners/2.278.0/externals/node12/bin/node]
20: 0x9ac928 node::Start(int, char**) [/home/runner/runners/2.278.0/externals/node12/bin/node]
21: 0x7f868588a0b3 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
22: 0x94a055  [/home/runner/runners/2.278.0/externals/node12/bin/node]
```

### Reproduction

**Action YAML**

```yaml
name: Deploy Function
on: 
  push:
    branches:
      - master
      - develop
jobs:
  build:
    name: Build Node ${{ matrix.node }} and {{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Build
        run: yarn compile
      - name: Set branch-based environment variables
        uses: iamtheyammer/branch-env-vars@v1.0.3
        with:
          FUNCTION_NAME: |
            master:xxxxxxx
            develop:xxxxxxx-dev
          ENV_VARS: |
            master: ${{ secrets.ENV_VARS_MASTER}}
            develop: ${{ secrets.ENV_VARS_DEVELOP}}
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          project_id: xxxxxxxxx
          name: ${{ env.FUNCTION_NAME }}
          entry_point: xxxxxxxxx
          runtime: nodejs14
          credentials: ${{ secrets.GCP_SECRET }}
          region: europe-west3
          memory_mb: 512MB
          env_vars: ${{ env.ENV_VARS }}
```
